arch:
  - amd64
  - ppc64le
language: go

go:
  - 1.7
  - 1.8
  - 1.13
  - 1.14
  - 1.15
jobs:
 exclude:
  - go: 1.7
    arch: ppc64le
  - go: 1.8
    arch: ppc64le
      
before_install:
  - go get github.com/mattn/goveralls
  - go get golang.org/x/tools/cmd/cover
script:
  - $HOME/gopath/bin/goveralls -repotoken ca4cRbwqOXDZBv39XjjxoXDDUnwEA7klw
